language: python
python:
  - "3.9"
os:
  - linux

git:
  depth: 1

env:
  - PLATFORMIO_PROJECT_DIR="examples/HELLO"
  - PLATFORMIO_PROJECT_DIR="examples/UNISTD"
  - PLATFORMIO_PROJECT_DIR="examples/pico-pioasm-ws2812"
  - PLATFORMIO_PROJECT_DIR="examples/pico-tft-st7789"
  - PLATFORMIO_PROJECT_DIR="examples/pico-usb-webserver"
  - PLATFORMIO_PROJECT_DIR="examples/pico-wasm3-dino-game"
  - PLATFORMIO_PROJECT_DIR="examples/pico-hello"
  - PLATFORMIO_PROJECT_DIR="examples/pico-ardiuno"
  - PLATFORMIO_PROJECT_DIR="examples/pico-cmsis-dap"

install:
  - pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
  - qio platform install file://.

script:
  - qio run -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
