version: 2
jobs:
  build:
    # branches:
    #   only:
    #     - "pio"
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "Install"
          command: |
            apt install -y git
            git submodule update --init --recursive
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            pio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/pico-hello
            pio run -d examples/pico-ardiuno
            pio run -d examples/pico-cmsis-dap
            pio run -d examples/pico-pioasm-ws2812
            pio run -d examples/pico-tft-st7789
            pio run -d examples/UNISTD
            pio run -d examples/HELLO
            pio run -d examples/pico-ardiuno
            pio run -d examples/pico-usb-webserver
            pio run -d examples/pico-wasm3-dino-game

workflows:
    version: 2
    run_ci:
        jobs:
          - build
