version: 2.1
jobs:
  build:
    branches:
      only:
        - qio
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "install"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install file://.
      - run:
          name: "Build"
          command: |
            pio run -d examples/pico-hello
            pio run -d examples/pico-pioasm-ws2812
            pio run -d examples/pico-tft-st7789
            pio run -d examples/UNISTD
            pio run -d examples/HELLO
            pio run -d examples/pico-usb-webserver
            pio run -d examples/pico-wasm3-dino-game
            pio run -d examples/pico-hello
            pio run -d examples/pico-ardiuno
            pio run -d examples/pico-cmsis-dap

workflows:
    version: 2
    run_ci:
        jobs:
          - build

