name: CI

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.md'
      - '**.yml'

env:
  UPLOAD_BUILD: false

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        # check_library: disable
        # skip_preprocessor: disable
        # exclude_check: ./project/
        enable: all #performance,portability,warning
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        # platform: disable
        std: c11
        output_file: ./cppcheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: report
        path: cppcheck.txt

  build:
    if: github.repository == 'OS-Q/P67'
    strategy:
      fail-fast: false
      matrix:
        examples:
        # os: [ubuntu-latest]
          - "Arduino/bg96/bg96_i2c_Si7021"
          - "Arduino/bg96/bg96_dss_dns"
          - "Arduino/bg96/bg96_client_http"

    runs-on: ubuntu-latest #${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        if: github.repository == 'OS-Q/P67'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/releases/latest/download/S03.zip
          qio platform install file://.

      - name: Build
        id: build
        if: success()
        run: |
          mkdir examples/${{ matrix.examples }}/build
          pio run -d examples/${{ matrix.examples }} > examples/${{ matrix.examples }}/build/log.txt
          echo "::set-output name=status::success"

      - name: Upload
        if: steps.build.outputs.status == 'success' && env.UPLOAD_BUILD
        uses: actions/upload-artifact@v2
        with:
          name: CI_Upload
          path: examples/${{ matrix.examples }}/build
